/**
 * sw.js - GENERATED by tools/build-sw.mjs. Do not edit by hand.
 *
 * Offline-first service worker: precaches the entire static app shell so the
 * Mishna Poster Generator works with no network connection and can be copied
 * to a USB drive and served locally. Sefaria API calls are network-first with
 * no offline fallback (the bundled content in assets/content covers the offline
 * example); everything else is cache-first.
 *
 * Release versioning: VERSION is the release number from package.json (kept
 * in lock-step with assets/js/version.js) and the cache name carries both the
 * release version and a content hash, so every release starts a fresh cache,
 * old caches are deleted on activate, and online users pick up the new build
 * automatically (the page also asks this worker for updates while it is open).
 */
const VERSION = '1.1.0';
const CACHE = 'mishna-poster-v1.1.0-4eb0575c003b';
const PRECACHE = [
  "index.html",
  "manifest.webmanifest",
  "robots.txt",
  "./",
  "assets/css/fonts.css",
  "assets/css/main.css",
  "assets/css/poster.css",
  "assets/js/content.js",
  "assets/js/hebrew.js",
  "assets/js/i18n.js",
  "assets/js/main.js",
  "assets/js/mishnah-index.js",
  "assets/js/pdf.js",
  "assets/js/poster.js",
  "assets/js/profiles.js",
  "assets/js/schedule.js",
  "assets/js/sefaria.js",
  "assets/js/settings.js",
  "assets/js/version.js",
  "assets/vendor/html2canvas.min.js",
  "assets/vendor/jspdf.umd.min.js",
  "assets/fonts/david-hebrew-400.woff2",
  "assets/fonts/david-hebrew-500.woff2",
  "assets/fonts/david-hebrew-700.woff2",
  "assets/fonts/david-latin-400.woff2",
  "assets/fonts/david-latin-500.woff2",
  "assets/fonts/david-latin-700.woff2",
  "assets/fonts/frl-hebrew-300.woff2",
  "assets/fonts/frl-hebrew-400.woff2",
  "assets/fonts/frl-hebrew-500.woff2",
  "assets/fonts/frl-hebrew-700.woff2",
  "assets/fonts/frl-hebrew-900.woff2",
  "assets/fonts/frl-latin-300.woff2",
  "assets/fonts/frl-latin-400.woff2",
  "assets/fonts/frl-latin-500.woff2",
  "assets/fonts/frl-latin-700.woff2",
  "assets/fonts/frl-latin-900.woff2",
  "assets/fonts/heebo-hebrew-300.woff2",
  "assets/fonts/heebo-hebrew-400.woff2",
  "assets/fonts/heebo-hebrew-600.woff2",
  "assets/fonts/heebo-hebrew-800.woff2",
  "assets/fonts/heebo-latin-300.woff2",
  "assets/fonts/heebo-latin-400.woff2",
  "assets/fonts/heebo-latin-600.woff2",
  "assets/fonts/heebo-latin-800.woff2",
  "assets/fonts/miriam-hebrew-400.woff2",
  "assets/fonts/miriam-hebrew-700.woff2",
  "assets/fonts/miriam-latin-400.woff2",
  "assets/fonts/miriam-latin-700.woff2",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/maskable-512.png",
  "assets/content/index.json",
  "assets/content/mishnah.json"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(
      keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)),
    )).then(() => self.clients.claim()),
  );
});

// The page can ask which release this worker serves (update banner wording).
self.addEventListener('message', (event) => {
  const data = event.data;
  if (data && data.type === 'GET_VERSION') {
    const reply = { type: 'VERSION', version: VERSION, cache: CACHE };
    if (event.ports && event.ports[0]) event.ports[0].postMessage(reply);
    else if (event.source && event.source.postMessage) event.source.postMessage(reply);
  }
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Never try to cache the live Sefaria API - always go to the network.
  if (url.hostname.endsWith('sefaria.org')) return;

  // Same-origin: cache-first, falling back to network, then the app shell.
  if (url.origin === self.location.origin) {
    event.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
        return res;
      }).catch(() => caches.match('index.html'))),
    );
  }
});
