#!/usr/bin/env node
/**
 * tools/build-sw.mjs - regenerate sw.js's precache list from the actual files
 * on disk, so the offline app shell never drifts out of sync with the repo.
 *
 * Release versioning: the release version is read from package.json (the
 * single source of truth). Every release bumps it; this tool then stamps it
 * into BOTH assets/js/version.js (shown in the UI) and sw.js (cache name +
 * VERSION constant), so shipped app code, the service worker, and the cache
 * identity can never disagree. The cache name keeps a content hash too, so a
 * forgotten version bump can still never serve a stale shell.
 *
 * Usage: node tools/build-sw.mjs
 */
import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const pkg = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const VERSION = String(pkg.version || '0.0.0');
if (!/^\d+\.\d+\.\d+/.test(VERSION)) {
  console.error(`package.json version "${VERSION}" is not semver (MAJOR.MINOR.PATCH)`);
  process.exit(1);
}

const ROOTS = ['assets/css', 'assets/js', 'assets/vendor', 'assets/fonts', 'assets/icons', 'assets/content'];
const TOP = ['index.html', 'manifest.webmanifest', 'robots.txt'];

function walk(dir) {
  const out = [];
  for (const name of readdirSync(path.join(ROOT, dir))) {
    const rel = `${dir}/${name}`;
    const st = statSync(path.join(ROOT, rel));
    if (st.isDirectory()) out.push(...walk(rel));
    else if (!name.startsWith('.')) out.push(rel);
  }
  return out;
}

// Keep the UI's version module in lock-step with package.json before the
// precache list is built, so version.js is always precached and current.
writeFileSync(
  path.join(ROOT, 'assets/js/version.js'),
  `/**
 * version.js - GENERATED by tools/build-sw.mjs from package.json. Do not edit.
 *
 * The human-facing release version of the app. Bump package.json's "version"
 * for every release and rerun \`node tools/build-sw.mjs\`; the service worker
 * cache name carries this version too, so every release invalidates old caches
 * and online users receive the update (main.js checks for it proactively).
 */
export const APP_VERSION = '${VERSION}';
`,
);

const files = [...TOP, './', ...ROOTS.flatMap(walk)]
  .filter((f) => !f.endsWith('LICENSE-html2canvas') && !f.endsWith('LICENSE-jspdf'));

// Content hash across all precached files -> cache version (auto-busts on change).
const hash = crypto.createHash('sha1');
for (const f of files) {
  if (f === './') continue;
  try { hash.update(readFileSync(path.join(ROOT, f))); } catch { /* './' */ }
}
const buildHash = hash.digest('hex').slice(0, 12);

const sw = `/**
 * sw.js - GENERATED by tools/build-sw.mjs. Do not edit by hand.
 *
 * Offline-first service worker: precaches the entire static app shell so the
 * Mishna Poster Generator works with no network connection and can be copied
 * to a USB drive and served locally. Sefaria API calls are network-first with
 * no offline fallback (the bundled content in assets/content covers the offline
 * example); everything else is cache-first.
 *
 * Release versioning: VERSION is the release number from package.json (kept
 * in lock-step with assets/js/version.js) and the cache name carries both the
 * release version and a content hash, so every release starts a fresh cache,
 * old caches are deleted on activate, and online users pick up the new build
 * automatically (the page also asks this worker for updates while it is open).
 */
const VERSION = '${VERSION}';
const CACHE = 'mishna-poster-v${VERSION}-${buildHash}';
const PRECACHE = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(
      keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)),
    )).then(() => self.clients.claim()),
  );
});

// The page can ask which release this worker serves (update banner wording).
self.addEventListener('message', (event) => {
  const data = event.data;
  if (data && data.type === 'GET_VERSION') {
    const reply = { type: 'VERSION', version: VERSION, cache: CACHE };
    if (event.ports && event.ports[0]) event.ports[0].postMessage(reply);
    else if (event.source && event.source.postMessage) event.source.postMessage(reply);
  }
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Never try to cache the live Sefaria API - always go to the network.
  if (url.hostname.endsWith('sefaria.org')) return;

  // Same-origin: cache-first, falling back to network, then the app shell.
  if (url.origin === self.location.origin) {
    event.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
        return res;
      }).catch(() => caches.match('index.html'))),
    );
  }
});
`;

writeFileSync(path.join(ROOT, 'sw.js'), sw);
console.log(`sw.js written: ${files.length} files, version ${VERSION}, cache mishna-poster-v${VERSION}-${buildHash}`);
