#!/usr/bin/env node
/**
 * tools/build-sw.mjs - regenerate sw.js's precache list from the actual files
 * on disk, so the offline app shell never drifts out of sync with the repo.
 *
 * Usage: node tools/build-sw.mjs
 */
import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const ROOTS = ['assets/css', 'assets/js', 'assets/vendor', 'assets/fonts', 'assets/icons', 'assets/content'];
const TOP = ['index.html', 'manifest.webmanifest'];

function walk(dir) {
  const out = [];
  for (const name of readdirSync(path.join(ROOT, dir))) {
    const rel = `${dir}/${name}`;
    const st = statSync(path.join(ROOT, rel));
    if (st.isDirectory()) out.push(...walk(rel));
    else if (!name.startsWith('.')) out.push(rel);
  }
  return out;
}

const files = [...TOP, './', ...ROOTS.flatMap(walk)]
  .filter((f) => !f.endsWith('LICENSE-html2canvas') && !f.endsWith('LICENSE-jspdf'));

// Content hash across all precached files -> cache version (auto-busts on change).
const hash = crypto.createHash('sha1');
for (const f of files) {
  if (f === './') continue;
  try { hash.update(readFileSync(path.join(ROOT, f))); } catch { /* './' */ }
}
const version = hash.digest('hex').slice(0, 12);

const sw = `/**
 * sw.js - GENERATED by tools/build-sw.mjs. Do not edit by hand.
 *
 * Offline-first service worker: precaches the entire static app shell so the
 * Mishna Poster Generator works with no network connection and can be copied
 * to a USB drive and served locally. Sefaria API calls are network-first with
 * no offline fallback (the bundled content in assets/content covers the offline
 * example); everything else is cache-first.
 */
const CACHE = 'mishna-poster-${version}';
const PRECACHE = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(
      keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)),
    )).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Never try to cache the live Sefaria API - always go to the network.
  if (url.hostname.endsWith('sefaria.org')) return;

  // Same-origin: cache-first, falling back to network, then the app shell.
  if (url.origin === self.location.origin) {
    event.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
        return res;
      }).catch(() => caches.match('index.html'))),
    );
  }
});
`;

writeFileSync(path.join(ROOT, 'sw.js'), sw);
console.log(`sw.js written: ${files.length} files, cache mishna-poster-${version}`);
